from turtle import *
#coordonnées x de la ligne
width = -14
#coordonnées y de la ligne
height = 14
#Taille d'un pixel
pixelSize = 23

up()
pensize(pixelSize)
speed(pixelSize / 2)
#1ère ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(15 * pixelSize)
down()
forward(pixelSize)
up()
#2ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(13 * pixelSize)
down()
forward(3 * pixelSize)
up()
#3ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
up()
forward(10 * pixelSize)
down()
forward(4 * pixelSize)
up()
#4ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(3 * pixelSize)
up()
forward(7 * pixelSize)
down()
forward(2 * pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#5ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(5 * pixelSize)
up()
forward(4 * pixelSize)
down()
forward(2 * pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
up()
#6ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("black")
forward(7 * pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("white")
forward(2 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#7ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(6 * pixelSize)
pencolor("white")
forward(2 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#8ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("white")
forward(2 * pixelSize)
pencolor("orange")
forward(10 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
up()
#9ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("white")
forward(2 * pixelSize)
pencolor("orange")
forward(11 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
up()
#10ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(2 * pixelSize)
down()
forward(pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("orange")
forward(13 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
up()
#11ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(2 * pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(15 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#12ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(2 * pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(10 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("black")
forward(6 * pixelSize)
up()
#13ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(3 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("orange")
forward(5 * pixelSize)
pencolor("black")
forward(4 * pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(5 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#14ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(3 * pixelSize)
pencolor("black")
forward(4 * pixelSize)
pencolor("orange")
forward(4 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(6 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#15ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(3 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(5 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(8 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#16ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(2 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("orange")
forward(8 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("black")
forward(5 * pixelSize)
pencolor("orange")
forward(2 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#17ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
down()
forward(4 * pixelSize)
pencolor("white")
forward(4 * pixelSize)
pencolor("orange")
forward(7 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(pixelSize)
pencolor("orange")
forward(pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("orange")
forward(4 * pixelSize)
pencolor("black")
forward(4 * pixelSize)
up()
#18ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
down()
forward(pixelSize)
pencolor("white")
forward(3 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
pencolor("white")
forward(4 * pixelSize)
pencolor("orange")
forward(4 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("black")
forward(3 * pixelSize)
pencolor("orange")
forward(8 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
up()
#19ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
down()
forward(pixelSize)
pencolor("white")
forward(5 * pixelSize)
pencolor("black")
forward(3 * pixelSize)
pencolor("white")
forward(2 * pixelSize)
pencolor("black")
forward(5 * pixelSize)
pencolor("orange")
forward(11 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#20ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
down()
forward(pixelSize)
pencolor("white")
forward(8 * pixelSize)
pencolor("black")
forward(5 * pixelSize)
pencolor("orange")
forward(13 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#21ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
down()
forward(pixelSize)
pencolor("white")
forward(7 * pixelSize)
pencolor("orange")
forward(19 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#22ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
down()
forward(pixelSize)
pencolor("white")
forward(6 * pixelSize)
pencolor("orange")
forward(20 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#23ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
down()
forward(pixelSize)
pencolor("white")
forward(7 * pixelSize)
pencolor("orange")
forward(18 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#24ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("white")
forward(2 * pixelSize)
pencolor("orange")
forward(3 * pixelSize)
pencolor("white")
forward(pixelSize)
pencolor("orange")
forward(18 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#25ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(pixelSize)
down()
forward(pixelSize)
pencolor("white")
forward(3 * pixelSize)
pencolor("orange")
forward(20 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#26ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(2 * pixelSize)
down()
forward(pixelSize)
pencolor("orange")
forward(21 * pixelSize)
pencolor("black")
forward(pixelSize)
up()
#27ème ligne
goto(width * pixelSize,height * pixelSize)
height -= 1
forward(3 * pixelSize)
down()
pencolor("black")
forward(2 * pixelSize)
pencolor("orange")
forward(17 * pixelSize)
pencolor("black")
forward(2 * pixelSize)
up()
#28ème ligne
goto(width * pixelSize,height * pixelSize)
forward(5 * pixelSize)
down()
forward(17 * pixelSize)
